/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gold.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Air_Jordan_One_not_smoothed_V02_lambert2_0.geometry} material={materials['Scratched Gold']} position={[-4.58, 0.48, 1.87]} scale={0.68} />
    </group>
  )
}

useGLTF.preload('/gold.gltf')
