/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 right.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/right.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.id_Punta001.geometry} material={materials.Default} position={[-0.75, 0.03, -0.93]} rotation={[0, 0.01, 0]} scale={6.59} />
    </group>
  )
}

useGLTF.preload('/right.glb')
