/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 AKQAlogo.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/AKQAlogo.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="path15948" position={[0.85, 0.14, -1.71]} rotation={[1.55, 0, 0]} scale={1.8}>
          <mesh name="path15948_1" geometry={nodes.path15948_1.geometry} material={materials['SVGMat.001']} />
          <mesh name="path15948_2" geometry={nodes.path15948_2.geometry} material={materials['SVGMat.002']} />
          <mesh name="path15948_3" geometry={nodes.path15948_3.geometry} material={materials['SVGMat.003']} />
          <mesh name="path15948_4" geometry={nodes.path15948_4.geometry} material={materials['SVGMat.004']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/AKQAlogo.glb')
