/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 AKQA.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/AKQA.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="akqa" geometry={nodes.akqa.geometry} material={materials.black} position={[-0.04, 0.21, -0.43]} rotation={[1.55, 0, 0]} scale={1.8} />
      </group>
    </group>
  )
}

useGLTF.preload('/AKQA.glb')
